name: Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      DOTNET_INSTALL_DIR: "/usr/lib64/dotnet"
    
    runs-on: ubuntu-latest-ppc64le

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with: 
          nuget-version: latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.115'

      - name: Restore dependencies
        working-directory: ./RecurrenceCalculator
        run: dotnet restore $SOLUTION

      - name: Build
        working-directory: ./RecurrenceCalculator
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        working-directory: ./RecurrenceCalculator
        run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal
